-- =============================================================================
--  IPHIPI database schema (libSQL / SQLite — also valid Postgres)
--
--  Identifiers are ULIDs (sortable, no UUID extension required).
--  JSON fields are TEXT (libSQL) / JSONB (Postgres) — DAL handles the difference.
--  Timestamps are unix epoch seconds (INTEGER) for portability.
-- =============================================================================

CREATE TABLE IF NOT EXISTS candidates (
  id           TEXT PRIMARY KEY,
  email        TEXT,
  name         TEXT,
  created_at   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
  id              TEXT PRIMARY KEY,
  slug            TEXT UNIQUE NOT NULL,
  title           TEXT NOT NULL,
  department      TEXT NOT NULL,
  level           TEXT NOT NULL,
  location        TEXT NOT NULL,
  jd_md           TEXT NOT NULL,            -- full markdown JD
  jd_struct_json  TEXT NOT NULL,            -- { responsibilities, must_haves, nice_to_haves, ... }
  weights_json    TEXT NOT NULL             -- per-skill scoring weights
);

CREATE TABLE IF NOT EXISTS applications (
  id                     TEXT PRIMARY KEY,
  candidate_id           TEXT NOT NULL REFERENCES candidates(id),
  job_id                 TEXT REFERENCES jobs(id),       -- null = generic, not tied to a role
  resume_blob_url        TEXT NOT NULL,
  resume_filename        TEXT NOT NULL,
  context_profile_json   TEXT,                            -- output of Agent 1
  match_score            INTEGER,                         -- 0..100
  match_breakdown_json   TEXT,
  status                 TEXT NOT NULL,                   -- 'parsing'|'ready'|'interviewing'|'completed'
  created_at             INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_applications_candidate ON applications(candidate_id);
CREATE INDEX IF NOT EXISTS idx_applications_job       ON applications(job_id);

-- Cached ranking of all IPHIPI jobs for a candidate's resume (powers /match-me)
CREATE TABLE IF NOT EXISTS role_match_runs (
  id           TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES candidates(id),
  scored_at    INTEGER NOT NULL,
  results_json TEXT NOT NULL                              -- ranked array of jobs + scores + rationales
);

CREATE INDEX IF NOT EXISTS idx_match_runs_candidate ON role_match_runs(candidate_id);

CREATE TABLE IF NOT EXISTS interview_sessions (
  id               TEXT PRIMARY KEY,
  application_id   TEXT NOT NULL REFERENCES applications(id),
  status           TEXT NOT NULL,                         -- 'pending'|'live'|'completed'|'abandoned'
  target_role      TEXT NOT NULL,                         -- snapshot of job title at session start
  agenda_json      TEXT NOT NULL,                         -- generated by orchestrator at start
  started_at       INTEGER NOT NULL,
  ended_at         INTEGER
);

CREATE INDEX IF NOT EXISTS idx_sessions_application ON interview_sessions(application_id);

CREATE TABLE IF NOT EXISTS interview_turns (
  id                    TEXT PRIMARY KEY,
  session_id            TEXT NOT NULL REFERENCES interview_sessions(id),
  turn_index            INTEGER NOT NULL,
  speaker               TEXT NOT NULL,                    -- 'agent' | 'candidate'
  content               TEXT NOT NULL,
  agent_intent          TEXT,                             -- orchestrator decision label
  difficulty            INTEGER,                          -- 1..5
  audio_metrics_json    TEXT,                             -- per Agent 3 input
  visual_metrics_json   TEXT,                             -- per Agent 4 input
  ts                    INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_turns_session ON interview_turns(session_id, turn_index);

CREATE TABLE IF NOT EXISTS agent_evaluations (
  id            TEXT PRIMARY KEY,
  session_id    TEXT NOT NULL REFERENCES interview_sessions(id),
  turn_id       TEXT REFERENCES interview_turns(id),
  agent_key     TEXT NOT NULL,                            -- 'audio'|'visual'|'technical'
  dimension     TEXT NOT NULL,                            -- 'confidence'|'clarity'|... (see plan §5)
  score         REAL NOT NULL,                            -- 0..1
  evidence_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_evals_session   ON agent_evaluations(session_id);
CREATE INDEX IF NOT EXISTS idx_evals_dimension ON agent_evaluations(session_id, dimension);

CREATE TABLE IF NOT EXISTS reports (
  id                       TEXT PRIMARY KEY,
  session_id               TEXT NOT NULL UNIQUE REFERENCES interview_sessions(id),
  summary_md               TEXT NOT NULL,
  scores_json              TEXT NOT NULL,                 -- per-dimension headline scores
  strengths_md             TEXT NOT NULL,
  improvements_md          TEXT NOT NULL,
  behavioral_insights_md   TEXT NOT NULL,
  next_steps_md            TEXT NOT NULL,
  generated_at             INTEGER NOT NULL
);
